#ifndef WALIA_TOKEN_H
#define WALIA_TOKEN_H

typedef enum {
  // Single-character tokens
  TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
  TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
  TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET, // Fixed Phase 11/13 indices
  TOKEN_COMMA, TOKEN_DOT, TOKEN_MINUS, TOKEN_PLUS,
  TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR,
  TOKEN_COLON, TOKEN_AMPERSAND, TOKEN_AT,
  TOKEN_TILDE, TOKEN_PIPE_CHAR,

  // One or two character tokens
  TOKEN_BANG, TOKEN_BANG_EQUAL,
  TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
  TOKEN_GREATER, TOKEN_GREATER_EQUAL,
  TOKEN_LESS, TOKEN_LESS_EQUAL,
  TOKEN_TILDE_EQUAL,
  TOKEN_PIPE,
  TOKEN_FAT_ARROW,
  TOKEN_RANGE,

  // Literals
  TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,

  // Keywords
  TOKEN_AND, TOKEN_CLASS, TOKEN_ELSE, TOKEN_FALSE,
  TOKEN_FOR, TOKEN_FUN, TOKEN_IF, TOKEN_NIL, TOKEN_OR,
  TOKEN_PRINT, TOKEN_RETURN, TOKEN_SUPER, TOKEN_THIS,
  TOKEN_TRUE, TOKEN_VAR, TOKEN_WHILE, TOKEN_IN,
  TOKEN_MATCH, TOKEN_GENE,
  TOKEN_WITH,     
  TOKEN_PARALLEL, 

  // Systems & Effects
  TOKEN_PERFORM, TOKEN_HANDLE, TOKEN_RESUME, TOKEN_TEST,
  TOKEN_LAYOUT, TOKEN_UNION, TOKEN_ASM, TOKEN_SYSCALL,
  TOKEN_ALLOC, TOKEN_RELEASE, TOKEN_SIZEOF,

  TOKEN_ASYNC, TOKEN_AWAIT,
  TOKEN_UNIT,

  TOKEN_ERROR,
  TOKEN_EOF
} TokenType;

typedef struct {
  TokenType type;
  const char* start;
  int length;
  int line;
} Token;

#endif